//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWBoardHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoWBoardHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povolání.
        /// </summary>
        internal static string _class {
            get {
                return ResourceManager.GetString("_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hráč.
        /// </summary>
        internal static string _player {
            get {
                return ResourceManager.GetString("_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rasa.
        /// </summary>
        internal static string _race {
            get {
                return ResourceManager.GetString("_race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warcraft.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuřivost krve.
        /// </summary>
        internal static string BloodFury {
            get {
                return ResourceManager.GetString("BloodFury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hráč {0}, vyber si svoje povolaní.
        /// </summary>
        internal static string ChooseClassPlayer {
            get {
                return ResourceManager.GetString("ChooseClassPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyber počet hráčů:.
        /// </summary>
        internal static string ChoosePlayers {
            get {
                return ResourceManager.GetString("ChoosePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výběr povolaní.
        /// </summary>
        internal static string classSelect {
            get {
                return ResourceManager.GetString("classSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyber povolání.
        /// </summary>
        internal static string ConfirmClass {
            get {
                return ResourceManager.GetString("ConfirmClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno Hráče.
        /// </summary>
        internal static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrubá hůl.
        /// </summary>
        internal static string RoughStaff {
            get {
                return ResourceManager.GetString("RoughStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šaman.
        /// </summary>
        internal static string Shaman {
            get {
                return ResourceManager.GetString("Shaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začít Hru.
        /// </summary>
        internal static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Původní bandáže.
        /// </summary>
        internal static string startingBandage {
            get {
                return ResourceManager.GetString("startingBandage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blesk.
        /// </summary>
        internal static string Thunder {
            get {
                return ResourceManager.GetString("Thunder", resourceCulture);
            }
        }
    }
}
